version: "3.8"

services:
  # servise for saves of temp data in RAM
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      - REDIS_HOST=0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - .:/redis
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    restart: always
    networks:
      - main

  # service for run of fastapi
  backend:
    build:
      context: ./app/backend/
      dockerfile: ./dockerfile
    command: sh -c "python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app/backend
    restart: always
    networks:
      - main

  bot:
    build:
      context: ./app/backend/
      dockerfile: ./dockerfile
    command: sh -c "python bot/main.py"
    volumes:
      - ./app/backend:/app/backend
    restart: always
    networks:
      - main

  # service for run vite
  frontend:
    build:
      context: ./app/frontend
      dockerfile: ./dockerfile
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 4173"
    ports:
      - "4173:4173"
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    restart: always
    networks:
      - main

  # service for redirect localhost to web
  tuna:
    image: yuccastream/tuna:latest
    command: start --all --tunnels-file=/opt/tuna.yml
    environment:
      - TUNA_TOKEN=${TUNA_TOKEN}
    depends_on:
      - backend
    volumes:
      - ./tuna.yml:/opt/tuna.yml
    restart: always
    networks:
        - main

# network for communication of services
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
