FROM python:3.12-alpine as base

WORKDIR /app/backend
COPY ./requirements.txt /app/backend/requirements.txt


RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/backend
